### ISSUE TITLE
Detect mouse wheel scroll events

### ISSUE THREAD

**Issue by dan-cristian** [wertarbyte/triggerhappy#10]
Hi. Is it possible to detect mouse wheel scroll events with thd? I could only get the mouse clicks events.

Thanks
Dan

**Comment by wertarbyte** [comment]
I just added support for REL_ events in version 0.4.0; feel free to test this new addition :-)

**Comment by dan-cristian** [comment]
Great news. Did a quick test and seems to work well. Many Thanks!
