### ISSUE TITLE
udev events not passed on Raspbian Stretch

### ISSUE THREAD

**Issue by guillaumezin** [wertarbyte/triggerhappy#22]
Hello,

On Rasbpian Stretch, triggerhappy version 0.5.0, I have to restart triggerhappy to detect my bluetooth keyboard (logitech harmony remote emulated). If I do a "sudo /usr/sbin/th-cmd --socket /var/run/thd.socket --passfd --udev", I have a segfault. "sudo /usr/sbin/th-cmd --socket /var/run/thd.socket --disable" gives "send_command: Transport endpoint is not connected".

Regards.

Guillaume

**Comment by guillaumezin** [comment]
The problem is the systemd socket that overwrite the configuration socket used for udev, I will report the bug on Debian mailing-list, this is more appropriate.

**Comment by adicarlo** [comment]
Would it be possible to cite the Debian bug number?

Does anyone have a workaround?

**Comment by guillaumezin** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=881533

The workaround is to delete "/lib/systemd/system/triggerhappy.socket"

**Comment by Pindar** [comment]
Because I stumbled over the same issue one can disable the socket by executing `sudo systemctl disable triggerhappy.socket`.

Thank you @guillaumezin for posting the workaround! Very helpful!
